FROM microsoft/windowsservercore

LABEL Description="Windows Server Core with Chocolatey installed"

MAINTAINER Daniel Scott-Raynsford

RUN powershell $ENV:chocolateyUseWindowsCompression = 'false'; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'));
